# Generated by Django 5.2.4 on 2025-07-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="brokerage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="gst",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sebi_charges",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="stamp_duty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="stt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
