# Generated by Django 5.2.4 on 2025-07-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_transaction_brokerage_transaction_gst_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="current_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
